### ISSUE TITLE
Incorrect Highlights

### ISSUE THREAD

**Issue by jnovack** [hangxingliu/vscode-systemd-support#1]
"Environment" is highlighted when it's in the description.

`[Unit]`, `[Service]`, `[Install]` are not highlighted.

**Comment by hangxingliu** [comment]
Try this extension file build from latest commit:

[vscode-systemd-support-0.2.0-dev.zip](https://github.com/hangxingliu/vscode-systemd-support/files/2453419/vscode-systemd-support-0.2.0-dev.zip)
 
I will test it in recent daily work and release new version.

**Comment by hangxingliu** [comment]
Install `vsix` file:

<https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix>

**Comment by hangxingliu** [comment]
Fix in new release version
