### ISSUE TITLE
Explain reason for fork

### ISSUE THREAD

**Issue by jeverling** [hangxingliu/vscode-systemd-support#2]
Hi, could you please explain why you decided to fork?
I think it would be helpful to put a short explanation in the README, so users can decide whether this fork works better for them than the forked project.

**Comment by tristangrimaux** [comment]
I second that motion!

**Comment by qm3ster** [comment]
I tried both from the extension store right now, and this one suggests known keys, the original (despite being more recently updated) seems to do only highlighting.

**Comment by hangxingliu** [comment]
Because it was a long time ago, I remember I forked this repo to enhance its auto-completion and other editor features, not just the syntax.

**Comment by hangxingliu** [comment]
The latest extension has been refactored and is moved to here <https://github.com/hangxingliu/vscode-systemd>
