### ISSUE TITLE
Misleading comment highlighting

### ISSUE THREAD

**Issue by fenhl** [hangxingliu/vscode-systemd-support#3]
Only lines starting with `#` or `;` are considered comments ([source](https://www.freedesktop.org/software/systemd/man/systemd.syntax.html)), however this extension also highlights text from a `#` in the middle of the line as a comment. In reality, this text will be considered part of the configuration value, leading to errors like the following:

```
Failed to parse the OOM score adjust value '-500 # make it less likely that Minecraft is killed when the system is out of RAM', ignoring: Invalid argument
```

**Comment by hangxingliu** [comment]
next version

**Comment by hangxingliu** [comment]
This bug has been fixed in the new version.The new version extension will be released on today.

And the latest extension has been refactored and is moved to here <https://github.com/hangxingliu/vscode-systemd>
